version: "3"

tasks:
  redis:
    summary: Runs the experiement with redis vector DB as our storage
    cmds:
      - python3 main.py --redis
  env:
    summary: start the environment
    cmds:
      - python3 venv -m venv
      - pip install -r requirements.txt